"""SQLAlchemy database models."""
from backend.app.models.base import (
    AssetType,
    NotificationType,
    SoftDeleteMixin,
    MultiTenantMixin,
    soft_delete_filter,
    include_deleted_filter,
    BooleanInt,
)

from backend.app.models.core import (
    Site,
    Asset,
    Meter,
    MeterReading,
    Bill,
    BillLineItem,
    Tariff,
    TariffRate,
    Notification,
)

from backend.app.models.enterprise import (
    DataSourceType,
    InvoiceStatus,
    DataSource,
    Measurement,
    Tenant,
    LeaseContract,
    Invoice,
    BatterySpecs,
)

from backend.app.models.bess import (
    BESSVendor,
    BESSModel,
    BESSDataset,
    BESSDataReading,
    BESSSimulationResult,
)

from backend.app.models.pv import (
    PVModuleCatalog,
    PVAssessment,
    PVSurface,
    PVDesignScenario,
    SiteMap,
    PlacementZone,
)

from backend.app.models.platform import (
    UserRole,
    AuditAction,
    FileStatus,
    PeriodStatus,
    NotificationChannel,
    Organization,
    User,
    OrgSite,
    UserSitePermission,
    AuditLog,
    FileAsset,
    PeriodLock,
    NotificationTemplate,
    NotificationPreference,
    NotificationDelivery,
    APIKey,
)

from backend.app.models.data_quality import (
    QualityIssueType,
    DataQualityRule,
    QualityIssue,
    MeterQualitySummary,
)

from backend.app.models.virtual_meters import (
    VirtualMeterType,
    VirtualMeter,
    VirtualMeterComponent,
    AllocationRule,
)

from backend.app.models.maintenance import (
    MaintenanceRuleType,
    MaintenanceCondition,
    MaintenanceRule,
    AssetCondition,
    MaintenanceAlert,
)

from backend.app.models.ai_forecasting import (
    AgentType,
    AgentSession,
    AgentMessage,
    Recommendation,
    ForecastJob,
    ForecastSeries,
)

from backend.app.models.control import (
    ControlRuleType,
    SafetyGateStatus,
    ControlRule,
    SafetyGate,
    ControlCommand,
)

from backend.app.models.integrations import (
    GatewayStatus,
    RegisterType,
    DataType,
    ByteOrder,
    Gateway,
    DeviceTemplate,
    TemplateRegister,
    ModbusRegister,
    CommunicationLog,
)

from backend.app.models.devices import (
    DeviceType,
    AuthType,
    ConfigSyncStatus,
    DatapointType,
    DatapointAggregation,
    CommandInputType,
    AlarmSeverity,
    AlarmCondition,
    PolicyAction,
    DeviceModel,
    DeviceProduct,
    Device,
    Datapoint,
    Command,
    AlarmRule,
    DevicePolicy,
    DeviceCertificate,
    DeviceDatapoint,
    CommandExecution,
    DeviceTelemetry,
    ProductRegisterMapping,
    RemoteModbusConfig,
    DeviceEvent,
)

from backend.app.models.telemetry import (
    AlarmStatus,
    AggregationPeriod,
    KPIType,
    DeviceAlarm,
    TelemetryAggregation,
    KPIDefinition,
    KPIValue,
    NoDataTracker,
)

__all__ = [
    "AssetType",
    "NotificationType",
    "SoftDeleteMixin",
    "MultiTenantMixin",
    "soft_delete_filter",
    "include_deleted_filter",
    "Site",
    "Asset",
    "Meter",
    "MeterReading",
    "Bill",
    "BillLineItem",
    "Tariff",
    "TariffRate",
    "Notification",
    "DataSourceType",
    "InvoiceStatus",
    "DataSource",
    "Measurement",
    "Tenant",
    "LeaseContract",
    "Invoice",
    "BatterySpecs",
    "BESSVendor",
    "BESSModel",
    "BESSDataset",
    "BESSDataReading",
    "BESSSimulationResult",
    "PVModuleCatalog",
    "PVAssessment",
    "PVSurface",
    "PVDesignScenario",
    "SiteMap",
    "PlacementZone",
    "UserRole",
    "AuditAction",
    "FileStatus",
    "PeriodStatus",
    "NotificationChannel",
    "Organization",
    "User",
    "OrgSite",
    "UserSitePermission",
    "AuditLog",
    "FileAsset",
    "PeriodLock",
    "NotificationTemplate",
    "NotificationPreference",
    "NotificationDelivery",
    "QualityIssueType",
    "DataQualityRule",
    "QualityIssue",
    "MeterQualitySummary",
    "VirtualMeterType",
    "VirtualMeter",
    "VirtualMeterComponent",
    "AllocationRule",
    "MaintenanceRuleType",
    "MaintenanceCondition",
    "MaintenanceRule",
    "AssetCondition",
    "MaintenanceAlert",
    "AgentType",
    "AgentSession",
    "AgentMessage",
    "Recommendation",
    "ForecastJob",
    "ForecastSeries",
    "ControlRuleType",
    "SafetyGateStatus",
    "ControlRule",
    "SafetyGate",
    "ControlCommand",
    "GatewayStatus",
    "RegisterType",
    "DataType",
    "ByteOrder",
    "Gateway",
    "DeviceTemplate",
    "TemplateRegister",
    "ModbusRegister",
    "CommunicationLog",
    "DeviceType",
    "AuthType",
    "ConfigSyncStatus",
    "DatapointType",
    "DatapointAggregation",
    "CommandInputType",
    "AlarmSeverity",
    "AlarmCondition",
    "PolicyAction",
    "DeviceModel",
    "DeviceProduct",
    "Device",
    "Datapoint",
    "Command",
    "AlarmRule",
    "DevicePolicy",
    "DeviceCertificate",
    "DeviceDatapoint",
    "CommandExecution",
    "DeviceTelemetry",
    "ProductRegisterMapping",
    "RemoteModbusConfig",
    "DeviceEvent",
    # Telemetry & Alarms
    "AlarmStatus",
    "AggregationPeriod",
    "KPIType",
    "DeviceAlarm",
    "TelemetryAggregation",
    "KPIDefinition",
    "KPIValue",
    "NoDataTracker",
]
