"""Notification model for AI agent alerts."""
from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import Column, Integer, String, DateTime, ForeignKey, Text, Enum
from sqlalchemy.orm import relationship
from backend.app.core.database import Base


class NotificationType(PyEnum):
    """Types of notifications generated by AI agents."""
    MISSING_METER = "missing_meter"
    PEAK_SHAVING_ALERT = "peak_shaving_alert"
    BILL_VARIANCE = "bill_variance"
    ANOMALY_DETECTED = "anomaly_detected"
    SOLAR_ROI_UPDATE = "solar_roi_update"
    MAINTENANCE_REQUIRED = "maintenance_required"
    OPTIMIZATION_SUGGESTION = "optimization_suggestion"


class Notification(Base):
    """
    Notification model for AI-generated alerts and recommendations.
    
    Agents create notifications based on analysis of meter data,
    bills, and optimization opportunities.
    """
    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, index=True)
    site_id = Column(Integer, ForeignKey("sites.id"), nullable=False, index=True)
    asset_id = Column(Integer, ForeignKey("assets.id"), nullable=True, index=True)
    
    notification_type = Column(Enum(NotificationType), nullable=False)
    severity = Column(String(20), default="info")
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    
    is_read = Column(Integer, default=0)
    is_resolved = Column(Integer, default=0)
    
    agent_name = Column(String(100), nullable=True)
    metadata = Column(Text, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    resolved_at = Column(DateTime, nullable=True)

    site = relationship("Site", back_populates="notifications")

    def __repr__(self) -> str:
        return f"<Notification(id={self.id}, type={self.notification_type.value}, title='{self.title}')>"
