"""Core Pydantic schemas for Site, Asset, Meter, Bill, Tariff, Notification, and related models."""
from datetime import datetime, date
from typing import Optional, List
from pydantic import BaseModel, Field, ConfigDict
from enum import Enum


class AssetType(str, Enum):
    """Types of assets in the electrical hierarchy (SLD)."""
    MAIN_BREAKER = "main_breaker"
    SUB_PANEL = "sub_panel"
    DISTRIBUTION_BOARD = "distribution_board"
    CONSUMER = "consumer"
    TRANSFORMER = "transformer"
    GENERATOR = "generator"
    SOLAR_INVERTER = "solar_inverter"
    BATTERY_STORAGE = "battery_storage"


class NotificationType(str, Enum):
    """Types of notifications generated by AI agents."""
    MISSING_METER = "missing_meter"
    PEAK_SHAVING_ALERT = "peak_shaving_alert"
    BILL_VARIANCE = "bill_variance"
    ANOMALY_DETECTED = "anomaly_detected"
    SOLAR_ROI_UPDATE = "solar_roi_update"
    MAINTENANCE_REQUIRED = "maintenance_required"
    OPTIMIZATION_SUGGESTION = "optimization_suggestion"


class SiteCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=255)
    address: Optional[str] = None
    city: Optional[str] = None
    country: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    timezone: str = "UTC"


class SiteUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    address: Optional[str] = None
    city: Optional[str] = None
    country: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    timezone: Optional[str] = None


class SiteResponse(BaseModel):
    id: int
    name: str
    address: Optional[str] = None
    city: Optional[str] = None
    country: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    timezone: str
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AssetCreate(BaseModel):
    site_id: int
    parent_id: Optional[int] = None
    name: str = Field(..., min_length=1, max_length=255)
    asset_type: AssetType
    description: Optional[str] = None
    rated_capacity_kw: Optional[float] = None
    rated_voltage: Optional[float] = None
    rated_current: Optional[float] = None
    is_critical: bool = False
    requires_metering: bool = True


class AssetUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    asset_type: Optional[AssetType] = None
    description: Optional[str] = None
    parent_id: Optional[int] = None
    rated_capacity_kw: Optional[float] = None
    rated_voltage: Optional[float] = None
    rated_current: Optional[float] = None
    is_critical: Optional[bool] = None
    requires_metering: Optional[bool] = None


class AssetResponse(BaseModel):
    id: int
    site_id: int
    parent_id: Optional[int] = None
    name: str
    asset_type: AssetType
    description: Optional[str] = None
    rated_capacity_kw: Optional[float] = None
    rated_voltage: Optional[float] = None
    rated_current: Optional[float] = None
    is_critical: bool = False
    requires_metering: bool = True
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class AssetTreeNode(BaseModel):
    id: int
    name: str
    asset_type: AssetType
    has_meter: bool = False
    meter_id: Optional[str] = None
    children: List["AssetTreeNode"] = []

    model_config = ConfigDict(from_attributes=True)


AssetTreeNode.model_rebuild()


class MeterCreate(BaseModel):
    site_id: int
    asset_id: Optional[int] = None
    meter_id: str = Field(..., min_length=1, max_length=100)
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    serial_number: Optional[str] = None
    is_active: bool = True
    is_bidirectional: bool = False


class MeterUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    asset_id: Optional[int] = None
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    serial_number: Optional[str] = None
    is_active: Optional[bool] = None
    is_bidirectional: Optional[bool] = None


class MeterResponse(BaseModel):
    id: int
    site_id: int
    asset_id: Optional[int] = None
    meter_id: str
    name: str
    description: Optional[str] = None
    manufacturer: Optional[str] = None
    model: Optional[str] = None
    serial_number: Optional[str] = None
    is_active: bool
    is_bidirectional: bool
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class MeterReadingCreate(BaseModel):
    meter_id: int
    timestamp: datetime
    energy_kwh: float
    power_kw: Optional[float] = None
    voltage: Optional[float] = None
    current: Optional[float] = None
    power_factor: Optional[float] = None
    reactive_power_kvar: Optional[float] = None
    apparent_power_kva: Optional[float] = None
    reading_type: str = "interval"


class MeterReadingResponse(BaseModel):
    id: int
    meter_id: int
    timestamp: datetime
    energy_kwh: float
    power_kw: Optional[float] = None
    voltage: Optional[float] = None
    current: Optional[float] = None
    power_factor: Optional[float] = None
    reactive_power_kvar: Optional[float] = None
    apparent_power_kva: Optional[float] = None
    reading_type: str
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class BillLineItemCreate(BaseModel):
    description: str
    category: Optional[str] = None
    quantity: Optional[float] = None
    unit: Optional[str] = None
    unit_price: Optional[float] = None
    amount: float


class BillLineItemResponse(BaseModel):
    id: int
    bill_id: int
    description: str
    category: Optional[str] = None
    quantity: Optional[float] = None
    unit: Optional[str] = None
    unit_price: Optional[float] = None
    amount: float
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class BillCreate(BaseModel):
    site_id: int
    tariff_id: Optional[int] = None
    bill_number: Optional[str] = None
    provider_name: Optional[str] = None
    period_start: date
    period_end: date
    issue_date: Optional[date] = None
    due_date: Optional[date] = None
    total_kwh: float
    total_amount: float
    currency: str = "USD"
    peak_kwh: Optional[float] = None
    off_peak_kwh: Optional[float] = None
    demand_kw: Optional[float] = None
    power_factor_penalty: Optional[float] = None
    taxes: Optional[float] = None
    other_charges: Optional[float] = None
    notes: Optional[str] = None
    line_items: List[BillLineItemCreate] = []


class BillUpdate(BaseModel):
    bill_number: Optional[str] = None
    provider_name: Optional[str] = None
    period_start: Optional[date] = None
    period_end: Optional[date] = None
    issue_date: Optional[date] = None
    due_date: Optional[date] = None
    total_kwh: Optional[float] = None
    total_amount: Optional[float] = None
    currency: Optional[str] = None
    tariff_id: Optional[int] = None
    notes: Optional[str] = None


class BillResponse(BaseModel):
    id: int
    site_id: int
    tariff_id: Optional[int] = None
    bill_number: Optional[str] = None
    provider_name: Optional[str] = None
    period_start: date
    period_end: date
    issue_date: Optional[date] = None
    due_date: Optional[date] = None
    total_kwh: float
    total_amount: float
    currency: str
    peak_kwh: Optional[float] = None
    off_peak_kwh: Optional[float] = None
    demand_kw: Optional[float] = None
    power_factor_penalty: Optional[float] = None
    taxes: Optional[float] = None
    other_charges: Optional[float] = None
    notes: Optional[str] = None
    is_validated: bool
    validation_variance_pct: Optional[float] = None
    created_at: datetime
    updated_at: datetime
    line_items: List[BillLineItemResponse] = []

    model_config = ConfigDict(from_attributes=True)


class BillValidationResult(BaseModel):
    bill_id: int
    is_valid: bool
    bill_total_kwh: float
    meter_total_kwh: float
    variance_kwh: float
    variance_percentage: float
    message: str


class UnmeteredAsset(BaseModel):
    asset_id: int
    asset_name: str
    asset_type: AssetType
    parent_id: Optional[int] = None
    parent_name: Optional[str] = None
    rated_capacity_kw: Optional[float] = None
    is_critical: bool = False
    hierarchy_path: List[str] = []


class GapAnalysisResult(BaseModel):
    site_id: int
    site_name: str
    total_assets: int
    metered_assets: int
    unmetered_assets: int
    coverage_percentage: float
    critical_unmetered_count: int
    unmetered_asset_list: List[UnmeteredAsset] = []
    recommendations: List[str] = []


class NotificationCreate(BaseModel):
    site_id: int
    asset_id: Optional[int] = None
    notification_type: NotificationType
    severity: str = "info"
    title: str
    message: str
    agent_name: Optional[str] = None
    extra_data: Optional[str] = None


class NotificationResponse(BaseModel):
    id: int
    site_id: int
    asset_id: Optional[int] = None
    notification_type: NotificationType
    severity: str
    title: str
    message: str
    is_read: bool
    is_resolved: bool
    agent_name: Optional[str] = None
    extra_data: Optional[str] = None
    created_at: datetime
    resolved_at: Optional[datetime] = None

    model_config = ConfigDict(from_attributes=True)


class TariffRateCreate(BaseModel):
    name: str
    rate_per_kwh: float
    time_start: Optional[str] = None
    time_end: Optional[str] = None
    days_of_week: Optional[str] = None
    season: Optional[str] = None
    tier_min_kwh: Optional[float] = None
    tier_max_kwh: Optional[float] = None


class TariffRateResponse(BaseModel):
    id: int
    tariff_id: int
    name: str
    rate_per_kwh: float
    time_start: Optional[str] = None
    time_end: Optional[str] = None
    days_of_week: Optional[str] = None
    season: Optional[str] = None
    tier_min_kwh: Optional[float] = None
    tier_max_kwh: Optional[float] = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class TariffCreate(BaseModel):
    """Create a new tariff schedule."""
    site_id: int
    name: str = Field(..., min_length=1, max_length=255)
    description: Optional[str] = None
    provider_name: Optional[str] = None
    effective_from: Optional[datetime] = None
    effective_to: Optional[datetime] = None
    currency: str = "USD"
    fixed_charge: float = 0.0
    demand_charge_per_kw: Optional[float] = None
    power_factor_threshold: Optional[float] = None
    power_factor_penalty_rate: Optional[float] = None
    tariff_type: str = "flat"
    rate_per_kwh: float = 0.12
    peak_rate: Optional[float] = None
    off_peak_rate: Optional[float] = None
    is_active: bool = True


class TariffUpdate(BaseModel):
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = None
    provider_name: Optional[str] = None
    effective_from: Optional[datetime] = None
    effective_to: Optional[datetime] = None
    currency: Optional[str] = None
    fixed_charge: Optional[float] = None
    demand_charge_per_kw: Optional[float] = None
    power_factor_threshold: Optional[float] = None
    power_factor_penalty_rate: Optional[float] = None
    tariff_type: Optional[str] = None
    rate_per_kwh: Optional[float] = None
    peak_rate: Optional[float] = None
    off_peak_rate: Optional[float] = None
    is_active: Optional[bool] = None


class TariffResponse(BaseModel):
    """Response for tariff queries."""
    id: int
    site_id: int
    name: str
    description: Optional[str] = None
    provider_name: Optional[str] = None
    effective_from: Optional[datetime] = None
    effective_to: Optional[datetime] = None
    currency: str
    fixed_charge: float
    demand_charge_per_kw: Optional[float] = None
    demand_rate_per_kw: Optional[float] = None
    power_factor_threshold: Optional[float] = None
    power_factor_penalty_rate: Optional[float] = None
    tariff_type: str = "flat"
    rate_per_kwh: float = 0.12
    peak_rate: Optional[float] = None
    off_peak_rate: Optional[float] = None
    is_active: bool
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SolarROIInput(BaseModel):
    """Input parameters for Solar ROI calculation."""
    annual_consumption_kwh: float
    average_electricity_rate: float
    system_size_kw: float
    installation_cost: float
    annual_solar_production_kwh_per_kw: float = 1400
    annual_degradation_rate: float = 0.005
    maintenance_cost_annual: float = 0.0
    incentive_amount: float = 0.0
    net_metering_rate: Optional[float] = None
    analysis_period_years: int = 25
    inflation_rate: float = 0.03


class SolarROIResult(BaseModel):
    """Result of Solar ROI calculation."""
    system_size_kw: float
    installation_cost: float
    year_one_production_kwh: float
    year_one_savings: float
    simple_payback_years: float
    net_present_value: float
    internal_rate_of_return: float
    lifetime_savings: float
    break_even_year: Optional[int]
    annual_projections: List[dict]
