"""
Device Templates Seed Data for SAVE-IT.AI
Pre-configured templates for common energy devices.
"""
from typing import List, Dict, Any


MANUFACTURERS = [
    {"name": "Schneider Electric", "country": "France", "website": "https://www.se.com"},
    {"name": "ABB", "country": "Switzerland", "website": "https://www.abb.com"},
    {"name": "Siemens", "country": "Germany", "website": "https://www.siemens.com"},
    {"name": "SMA Solar Technology", "country": "Germany", "website": "https://www.sma.de"},
    {"name": "Fronius International", "country": "Austria", "website": "https://www.fronius.com"},
    {"name": "Huawei", "country": "China", "website": "https://solar.huawei.com"},
    {"name": "SolarEdge", "country": "Israel", "website": "https://www.solaredge.com"},
    {"name": "Enphase Energy", "country": "USA", "website": "https://enphase.com"},
    {"name": "Tesla", "country": "USA", "website": "https://www.tesla.com"},
    {"name": "BYD", "country": "China", "website": "https://www.byd.com"},
    {"name": "LG Energy Solution", "country": "South Korea", "website": "https://www.lgensol.com"},
    {"name": "Pylontech", "country": "China", "website": "https://en.pylontech.com.cn"},
    {"name": "Janitza Electronics", "country": "Germany", "website": "https://www.janitza.com"},
    {"name": "Eastron", "country": "China", "website": "https://www.eastrongroup.com"},
    {"name": "Honeywell", "country": "USA", "website": "https://www.honeywell.com"},
    {"name": "Johnson Controls", "country": "Ireland", "website": "https://www.johnsoncontrols.com"},
    {"name": "Daikin", "country": "Japan", "website": "https://www.daikin.com"},
    {"name": "ABB E-Mobility", "country": "Switzerland", "website": "https://new.abb.com/ev-charging"},
    {"name": "ChargePoint", "country": "USA", "website": "https://www.chargepoint.com"},
    {"name": "Victron Energy", "country": "Netherlands", "website": "https://www.victronenergy.com"},
]


DEVICE_TEMPLATES: List[Dict[str, Any]] = [
    {
        "manufacturer": "Schneider Electric",
        "name": "PowerLogic PM5560",
        "model_number": "PM5560",
        "category": "power_meter",
        "protocol": "modbus_tcp",
        "description": "High-performance power and energy meter with advanced power quality analysis",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 15,
        "is_verified": True,
        "registers": [
            {"name": "voltage_l1_n", "address": 3027, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1-N Voltage"},
            {"name": "voltage_l2_n", "address": 3029, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L2-N Voltage"},
            {"name": "voltage_l3_n", "address": 3031, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L3-N Voltage"},
            {"name": "current_l1", "address": 3000, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1 Current"},
            {"name": "current_l2", "address": 3002, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L2 Current"},
            {"name": "current_l3", "address": 3004, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L3 Current"},
            {"name": "active_power_total", "address": 3060, "data_type": "float32", "unit": "kW", "scale_factor": 0.001, "function_code": 3, "description": "Total Active Power"},
            {"name": "reactive_power_total", "address": 3068, "data_type": "float32", "unit": "kVAR", "scale_factor": 0.001, "function_code": 3, "description": "Total Reactive Power"},
            {"name": "apparent_power_total", "address": 3076, "data_type": "float32", "unit": "kVA", "scale_factor": 0.001, "function_code": 3, "description": "Total Apparent Power"},
            {"name": "power_factor_total", "address": 3084, "data_type": "float32", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Total Power Factor"},
            {"name": "frequency", "address": 3110, "data_type": "float32", "unit": "Hz", "scale_factor": 1.0, "function_code": 3, "description": "Frequency"},
            {"name": "active_energy_import", "address": 3204, "data_type": "float32", "unit": "kWh", "scale_factor": 1.0, "function_code": 3, "description": "Total Active Energy Import"},
            {"name": "active_energy_export", "address": 3208, "data_type": "float32", "unit": "kWh", "scale_factor": 1.0, "function_code": 3, "description": "Total Active Energy Export"},
        ]
    },
    {
        "manufacturer": "ABB",
        "name": "M4M 30 Network Analyzer",
        "model_number": "M4M-30",
        "category": "power_meter",
        "protocol": "modbus_tcp",
        "description": "Compact three-phase network analyzer for electrical installations",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 15,
        "is_verified": True,
        "registers": [
            {"name": "voltage_l1_n", "address": 0x0000, "data_type": "uint32", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Phase L1-N Voltage"},
            {"name": "voltage_l2_n", "address": 0x0002, "data_type": "uint32", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Phase L2-N Voltage"},
            {"name": "voltage_l3_n", "address": 0x0004, "data_type": "uint32", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Phase L3-N Voltage"},
            {"name": "current_l1", "address": 0x000C, "data_type": "uint32", "unit": "A", "scale_factor": 0.001, "function_code": 3, "description": "Phase L1 Current"},
            {"name": "current_l2", "address": 0x000E, "data_type": "uint32", "unit": "A", "scale_factor": 0.001, "function_code": 3, "description": "Phase L2 Current"},
            {"name": "current_l3", "address": 0x0010, "data_type": "uint32", "unit": "A", "scale_factor": 0.001, "function_code": 3, "description": "Phase L3 Current"},
            {"name": "active_power_total", "address": 0x0028, "data_type": "int32", "unit": "kW", "scale_factor": 0.01, "function_code": 3, "description": "Total Active Power"},
            {"name": "power_factor_total", "address": 0x002E, "data_type": "int16", "unit": "", "scale_factor": 0.001, "function_code": 3, "description": "Total Power Factor"},
            {"name": "frequency", "address": 0x0030, "data_type": "uint16", "unit": "Hz", "scale_factor": 0.01, "function_code": 3, "description": "Frequency"},
            {"name": "active_energy_import", "address": 0x0040, "data_type": "uint32", "unit": "kWh", "scale_factor": 0.01, "function_code": 3, "description": "Total Active Energy Import"},
        ]
    },
    {
        "manufacturer": "Siemens",
        "name": "SENTRON PAC3200",
        "model_number": "PAC3200",
        "category": "power_meter",
        "protocol": "modbus_tcp",
        "description": "Compact power monitoring device for electrical installations",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 15,
        "is_verified": True,
        "registers": [
            {"name": "voltage_l1_n", "address": 1, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1-N Voltage"},
            {"name": "voltage_l2_n", "address": 3, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L2-N Voltage"},
            {"name": "voltage_l3_n", "address": 5, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L3-N Voltage"},
            {"name": "current_l1", "address": 13, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1 Current"},
            {"name": "current_l2", "address": 15, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L2 Current"},
            {"name": "current_l3", "address": 17, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L3 Current"},
            {"name": "active_power_total", "address": 25, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Total Active Power"},
            {"name": "reactive_power_total", "address": 27, "data_type": "float32", "unit": "VAR", "scale_factor": 1.0, "function_code": 3, "description": "Total Reactive Power"},
            {"name": "power_factor_total", "address": 37, "data_type": "float32", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Total Power Factor"},
            {"name": "frequency", "address": 55, "data_type": "float32", "unit": "Hz", "scale_factor": 1.0, "function_code": 3, "description": "Frequency"},
            {"name": "active_energy_import", "address": 801, "data_type": "float64", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Total Active Energy Import"},
        ]
    },
    {
        "manufacturer": "Eastron",
        "name": "SDM630 Modbus",
        "model_number": "SDM630",
        "category": "energy_meter",
        "protocol": "modbus_rtu",
        "description": "Three-phase multifunction energy meter with Modbus RTU",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 10,
        "is_verified": True,
        "registers": [
            {"name": "voltage_l1", "address": 0, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 4, "description": "Phase 1 Voltage"},
            {"name": "voltage_l2", "address": 2, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 4, "description": "Phase 2 Voltage"},
            {"name": "voltage_l3", "address": 4, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 4, "description": "Phase 3 Voltage"},
            {"name": "current_l1", "address": 6, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 4, "description": "Phase 1 Current"},
            {"name": "current_l2", "address": 8, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 4, "description": "Phase 2 Current"},
            {"name": "current_l3", "address": 10, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 4, "description": "Phase 3 Current"},
            {"name": "active_power_l1", "address": 12, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 4, "description": "Phase 1 Active Power"},
            {"name": "active_power_l2", "address": 14, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 4, "description": "Phase 2 Active Power"},
            {"name": "active_power_l3", "address": 16, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 4, "description": "Phase 3 Active Power"},
            {"name": "total_power", "address": 52, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 4, "description": "Total System Power"},
            {"name": "frequency", "address": 70, "data_type": "float32", "unit": "Hz", "scale_factor": 1.0, "function_code": 4, "description": "Frequency"},
            {"name": "import_kwh", "address": 72, "data_type": "float32", "unit": "kWh", "scale_factor": 1.0, "function_code": 4, "description": "Import Active Energy"},
            {"name": "export_kwh", "address": 74, "data_type": "float32", "unit": "kWh", "scale_factor": 1.0, "function_code": 4, "description": "Export Active Energy"},
        ]
    },
    {
        "manufacturer": "Janitza Electronics",
        "name": "UMG 96RM-E",
        "model_number": "UMG96RM-E",
        "category": "power_meter",
        "protocol": "modbus_tcp",
        "description": "Universal measurement device for electrical networks",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 15,
        "is_verified": True,
        "registers": [
            {"name": "voltage_l1_n", "address": 19000, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1-N Voltage"},
            {"name": "voltage_l2_n", "address": 19002, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L2-N Voltage"},
            {"name": "voltage_l3_n", "address": 19004, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "Phase L3-N Voltage"},
            {"name": "current_l1", "address": 19012, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "Phase L1 Current"},
            {"name": "active_power_total", "address": 19026, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Total Active Power"},
            {"name": "frequency", "address": 19050, "data_type": "float32", "unit": "Hz", "scale_factor": 1.0, "function_code": 3, "description": "Frequency"},
        ]
    },
    {
        "manufacturer": "SMA Solar Technology",
        "name": "Sunny Boy 5.0",
        "model_number": "SB5.0-1AV-41",
        "category": "inverter",
        "protocol": "modbus_tcp",
        "description": "Single-phase solar inverter for residential applications",
        "default_port": 502,
        "default_slave_id": 3,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "dc_power", "address": 30773, "data_type": "int32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "DC Power Input"},
            {"name": "ac_power", "address": 30775, "data_type": "int32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "AC Power Output"},
            {"name": "daily_yield", "address": 30517, "data_type": "uint64", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Daily Energy Yield"},
            {"name": "total_yield", "address": 30529, "data_type": "uint64", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Total Energy Yield"},
            {"name": "grid_voltage", "address": 30783, "data_type": "uint32", "unit": "V", "scale_factor": 0.01, "function_code": 3, "description": "Grid Voltage"},
            {"name": "grid_frequency", "address": 30803, "data_type": "uint32", "unit": "Hz", "scale_factor": 0.01, "function_code": 3, "description": "Grid Frequency"},
            {"name": "device_temperature", "address": 30953, "data_type": "int32", "unit": "C", "scale_factor": 0.1, "function_code": 3, "description": "Device Temperature"},
            {"name": "operating_status", "address": 30201, "data_type": "uint32", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Operating Status"},
        ]
    },
    {
        "manufacturer": "Fronius International",
        "name": "Fronius Symo 10.0-3-M",
        "model_number": "Symo10.0-3-M",
        "category": "inverter",
        "protocol": "modbus_tcp",
        "description": "Three-phase solar inverter for commercial applications",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "ac_power", "address": 40083, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "AC Power Output"},
            {"name": "ac_current", "address": 40071, "data_type": "float32", "unit": "A", "scale_factor": 1.0, "function_code": 3, "description": "AC Current"},
            {"name": "ac_voltage_l1", "address": 40079, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "AC Voltage L1"},
            {"name": "ac_frequency", "address": 40085, "data_type": "float32", "unit": "Hz", "scale_factor": 1.0, "function_code": 3, "description": "AC Frequency"},
            {"name": "dc_power", "address": 40101, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "DC Power Input"},
            {"name": "dc_voltage", "address": 40099, "data_type": "float32", "unit": "V", "scale_factor": 1.0, "function_code": 3, "description": "DC Voltage"},
            {"name": "energy_total", "address": 40093, "data_type": "float32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Total Energy Produced"},
            {"name": "cabinet_temperature", "address": 40107, "data_type": "float32", "unit": "C", "scale_factor": 1.0, "function_code": 3, "description": "Cabinet Temperature"},
        ]
    },
    {
        "manufacturer": "Huawei",
        "name": "SUN2000-10KTL-M1",
        "model_number": "SUN2000-10KTL",
        "category": "inverter",
        "protocol": "modbus_tcp",
        "description": "Commercial string inverter with smart features",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "pv1_voltage", "address": 32016, "data_type": "int16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "PV1 Voltage"},
            {"name": "pv1_current", "address": 32017, "data_type": "int16", "unit": "A", "scale_factor": 0.01, "function_code": 3, "description": "PV1 Current"},
            {"name": "pv2_voltage", "address": 32018, "data_type": "int16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "PV2 Voltage"},
            {"name": "pv2_current", "address": 32019, "data_type": "int16", "unit": "A", "scale_factor": 0.01, "function_code": 3, "description": "PV2 Current"},
            {"name": "input_power", "address": 32064, "data_type": "int32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Input Power"},
            {"name": "grid_voltage_a", "address": 32066, "data_type": "uint16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Grid Voltage Phase A"},
            {"name": "active_power", "address": 32080, "data_type": "int32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Active Power"},
            {"name": "daily_energy", "address": 32114, "data_type": "uint32", "unit": "kWh", "scale_factor": 0.01, "function_code": 3, "description": "Daily Energy Yield"},
            {"name": "total_energy", "address": 32106, "data_type": "uint32", "unit": "kWh", "scale_factor": 0.01, "function_code": 3, "description": "Total Energy Yield"},
            {"name": "inverter_temperature", "address": 32087, "data_type": "int16", "unit": "C", "scale_factor": 0.1, "function_code": 3, "description": "Inverter Temperature"},
        ]
    },
    {
        "manufacturer": "SolarEdge",
        "name": "SE10K Inverter",
        "model_number": "SE10K",
        "category": "inverter",
        "protocol": "modbus_tcp",
        "description": "Three-phase inverter with power optimizer support",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "ac_power", "address": 40083, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "AC Power Output"},
            {"name": "ac_frequency", "address": 40085, "data_type": "uint16", "unit": "Hz", "scale_factor": 0.01, "function_code": 3, "description": "AC Frequency"},
            {"name": "dc_power", "address": 40100, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "DC Power Input"},
            {"name": "dc_voltage", "address": 40098, "data_type": "uint16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "DC Voltage"},
            {"name": "temperature", "address": 40103, "data_type": "int16", "unit": "C", "scale_factor": 0.01, "function_code": 3, "description": "Heat Sink Temperature"},
            {"name": "lifetime_energy", "address": 40093, "data_type": "uint32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Lifetime Energy"},
            {"name": "status", "address": 40107, "data_type": "uint16", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Operating Status"},
        ]
    },
    {
        "manufacturer": "Tesla",
        "name": "Powerwall 2",
        "model_number": "Powerwall2",
        "category": "bess",
        "protocol": "https",
        "description": "Home battery system for energy storage",
        "default_port": 443,
        "default_polling_interval": 60,
        "is_verified": True,
        "registers": [
            {"name": "soc", "address": 0, "data_type": "float32", "unit": "%", "scale_factor": 1.0, "function_code": 0, "description": "State of Charge"},
            {"name": "power", "address": 1, "data_type": "float32", "unit": "W", "scale_factor": 1.0, "function_code": 0, "description": "Instantaneous Power"},
            {"name": "energy_remaining", "address": 2, "data_type": "float32", "unit": "Wh", "scale_factor": 1.0, "function_code": 0, "description": "Energy Remaining"},
            {"name": "grid_status", "address": 3, "data_type": "uint16", "unit": "", "scale_factor": 1.0, "function_code": 0, "description": "Grid Status"},
        ]
    },
    {
        "manufacturer": "BYD",
        "name": "Battery-Box Premium HVS",
        "model_number": "HVS",
        "category": "bess",
        "protocol": "modbus_tcp",
        "description": "High voltage battery system for commercial applications",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "soc", "address": 0x0101, "data_type": "uint16", "unit": "%", "scale_factor": 1.0, "function_code": 3, "description": "State of Charge"},
            {"name": "soh", "address": 0x0102, "data_type": "uint16", "unit": "%", "scale_factor": 1.0, "function_code": 3, "description": "State of Health"},
            {"name": "battery_voltage", "address": 0x0103, "data_type": "uint16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Battery Voltage"},
            {"name": "battery_current", "address": 0x0104, "data_type": "int16", "unit": "A", "scale_factor": 0.1, "function_code": 3, "description": "Battery Current"},
            {"name": "battery_power", "address": 0x0105, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Battery Power"},
            {"name": "battery_temperature", "address": 0x0106, "data_type": "int16", "unit": "C", "scale_factor": 0.1, "function_code": 3, "description": "Battery Temperature"},
            {"name": "max_charge_voltage", "address": 0x0107, "data_type": "uint16", "unit": "V", "scale_factor": 0.1, "function_code": 3, "description": "Max Charge Voltage"},
            {"name": "max_charge_current", "address": 0x0108, "data_type": "uint16", "unit": "A", "scale_factor": 0.1, "function_code": 3, "description": "Max Charge Current"},
        ]
    },
    {
        "manufacturer": "Pylontech",
        "name": "US3000C",
        "model_number": "US3000C",
        "category": "bess",
        "protocol": "modbus_rtu",
        "description": "Low voltage lithium battery module",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "pack_voltage", "address": 0, "data_type": "uint16", "unit": "mV", "scale_factor": 0.001, "function_code": 3, "description": "Pack Voltage"},
            {"name": "pack_current", "address": 1, "data_type": "int16", "unit": "A", "scale_factor": 0.1, "function_code": 3, "description": "Pack Current"},
            {"name": "soc", "address": 2, "data_type": "uint16", "unit": "%", "scale_factor": 1.0, "function_code": 3, "description": "State of Charge"},
            {"name": "cell_temp_max", "address": 3, "data_type": "int16", "unit": "C", "scale_factor": 0.1, "function_code": 3, "description": "Max Cell Temperature"},
            {"name": "cell_temp_min", "address": 4, "data_type": "int16", "unit": "C", "scale_factor": 0.1, "function_code": 3, "description": "Min Cell Temperature"},
        ]
    },
    {
        "manufacturer": "Victron Energy",
        "name": "MultiPlus-II 48/5000",
        "model_number": "MultiPlus-II",
        "category": "inverter",
        "protocol": "modbus_tcp",
        "description": "Inverter/charger with grid-tied and off-grid capability",
        "default_port": 502,
        "default_slave_id": 100,
        "default_polling_interval": 30,
        "is_verified": True,
        "registers": [
            {"name": "ac_in_power", "address": 12, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "AC Input Power"},
            {"name": "ac_out_power", "address": 23, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "AC Output Power"},
            {"name": "battery_voltage", "address": 26, "data_type": "uint16", "unit": "V", "scale_factor": 0.01, "function_code": 3, "description": "Battery Voltage"},
            {"name": "battery_current", "address": 27, "data_type": "int16", "unit": "A", "scale_factor": 0.1, "function_code": 3, "description": "Battery Current"},
            {"name": "battery_soc", "address": 30, "data_type": "uint16", "unit": "%", "scale_factor": 1.0, "function_code": 3, "description": "Battery SOC"},
            {"name": "battery_power", "address": 258, "data_type": "int16", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Battery Power"},
        ]
    },
    {
        "manufacturer": "ABB E-Mobility",
        "name": "Terra AC Wallbox",
        "model_number": "Terra-AC",
        "category": "ev_charger",
        "protocol": "modbus_tcp",
        "description": "AC wallbox for electric vehicle charging",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 60,
        "is_verified": True,
        "registers": [
            {"name": "charging_state", "address": 0, "data_type": "uint16", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Charging State"},
            {"name": "current_limit", "address": 1, "data_type": "uint16", "unit": "A", "scale_factor": 0.1, "function_code": 3, "description": "Current Limit"},
            {"name": "active_power", "address": 2, "data_type": "uint32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Active Power"},
            {"name": "energy_delivered", "address": 4, "data_type": "uint32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Energy Delivered"},
            {"name": "session_energy", "address": 6, "data_type": "uint32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Session Energy"},
        ]
    },
    {
        "manufacturer": "Schneider Electric",
        "name": "EVlink Home",
        "model_number": "EVH2S",
        "category": "ev_charger",
        "protocol": "modbus_tcp",
        "description": "Home EV charging station",
        "default_port": 502,
        "default_slave_id": 1,
        "default_polling_interval": 60,
        "is_verified": True,
        "registers": [
            {"name": "state", "address": 100, "data_type": "uint16", "unit": "", "scale_factor": 1.0, "function_code": 3, "description": "Charger State"},
            {"name": "power", "address": 102, "data_type": "uint32", "unit": "W", "scale_factor": 1.0, "function_code": 3, "description": "Charging Power"},
            {"name": "energy_session", "address": 104, "data_type": "uint32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Session Energy"},
            {"name": "energy_total", "address": 106, "data_type": "uint32", "unit": "Wh", "scale_factor": 1.0, "function_code": 3, "description": "Total Energy"},
        ]
    },
]


def get_manufacturers() -> List[Dict[str, Any]]:
    """Get list of manufacturers to seed."""
    return MANUFACTURERS


def get_device_templates() -> List[Dict[str, Any]]:
    """Get list of device templates to seed."""
    return DEVICE_TEMPLATES
